spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=food_user
spring.datasource.password=food_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
